# Site settings
title: "Faisal Alvi | WordPress & WooCommerce Solutions Architect"
description: "Building high-performing WordPress & WooCommerce solutions | Open-source contributor | 12+ years shaping enterprise-grade digital experiences"
author: "Faisal Alvi"
email: "faisal@example.com"
url: "https://faisal-alvi.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: UTC

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Faisal Alvi"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor